apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observers

resources:
  - ../../base

configMapGenerator:
  - name: prod-config
    envs:
      - ../../../../config/prod.env

generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source:
      kind: ConfigMap
      name: prod-config
      fieldPath: data.monitorUrlHome
    targets:
      - select:
          kind: Probe
          name: blog-external
        fieldPaths:
          - spec.targets.staticConfig.static.0
  - source:
      kind: ConfigMap
      name: prod-config
      fieldPath: data.monitorUrlSitemap
    targets:
      - select:
          kind: Probe
          name: blog-external
        fieldPaths:
          - spec.targets.staticConfig.static.1
  - source:
      kind: ConfigMap
      name: prod-config
      fieldPath: data.monitorUrlGhost
    targets:
      - select:
          kind: Probe
          name: blog-external
        fieldPaths:
          - spec.targets.staticConfig.static.2

