apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflared

resources:
  - ../../base
  # - servicemonitor.yaml  # Prometheus Operator CRD not installed
  - networkpolicy.yaml
  - namespace.yaml

configMapGenerator:
  - name: prod-config
    envs:
      - ../../../../config/prod.env

generatorOptions:
  disableNameSuffixHash: true

