apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observers

resources:
  - ../../base
  - namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: vmagent-scrape
    behavior: replace
    files:
      - scrape.yml=vmagent-scrape.yml
