apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds/monitoring.coreos.com_alertmanagers.yaml
  - crds/monitoring.coreos.com_podmonitors.yaml
  - crds/monitoring.coreos.com_probes.yaml
  - crds/monitoring.coreos.com_prometheuses.yaml
  - crds/monitoring.coreos.com_prometheusrules.yaml
  - crds/monitoring.coreos.com_servicemonitors.yaml
