apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog

resources:
  - ../../base
  - networkpolicy.yaml
  - networkpolicy-monitoring.yaml
  - hpa.yaml
  - namespace.yaml

configMapGenerator:
  - name: prod-config
    envs:
      - ../../../../config/prod.env

generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source:
      kind: ConfigMap
      name: prod-config
      fieldPath: data.domain
    targets:
      - select:
          kind: Ingress
          name: ghost
        fieldPaths:
          - spec.rules.0.host


