apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - mysql-statefulset.yaml
  - mysql-service.yaml
  - mysql-exporter-service.yaml
  - pvc-ghost-content.yaml
  - pdb.yaml

