apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
  - ../../base
  - servicemonitor.yaml
  - pdb.yaml
  - namespace.yaml

configMapGenerator:
  - name: prod-config
    envs:
      - ../../../../config/prod.env

generatorOptions:
  disableNameSuffixHash: true

